import InnerBanner from "../Components/InnerBanner/InnerBanner";
import Head from "next/head";
import React from "react";
import Layout from "../layout/index";
import Image from "next/image";
import Link from "next/link";
import SameLessTravel from "../Components/SameLessTravel/SameLessTravel";
import OurMission from "../Components/OurMission/OurMission";

const data = [
  {
    eyeBrow: "why us",
    title: "About us",
    imageUrl: "/images/about-banner.png",
  },
];
const semlessData = [
  {
    cardNum: "1",
    title: "Unrivaled Selection",
    desc: "Whether you're searching for the perfect hotel, seeking out the best attractions, or booking your next flight, we've got you covered with an unparalleled selection of options to suit every budget and preference.",
  },
  {
    cardNum: "2",
    title: "Ease and Convenience",
    desc: "Say goodbye to endless browsing and complicated booking processes. With our user-friendly interface and intuitive search tools, finding and booking your ideal travel arrangements has never been easier",
  },
  {
    cardNum: "3",
    title: "Best Price Guarantee",
    desc: "We're committed to offering you the best deals on hotels, attractions, and flights. With our competitive prices and exclusive discounts, you can rest assured that you're getting unbeatable value for your money.",
  },
  {
    cardNum: "4",
    title: "Expert Advice and Recommen dations",
    desc: "We're committed to offering you the best deals on hotels, attractions, and flights. With our competitive prices and exclusive discounts, you can rest assured that you're getting unbeatable value for your money.",
  },
  {
    cardNum: "5",
    title: "Secure and Reliable",
    desc: "Say goodbye to endless browsing and complicated booking processes. With our user-friendly interface and intuitive search tools, finding and booking your ideal travel arrangements has never been easier",
  },
  {
    cardNum: "6",
    title: "Exceptional Customer Service",
    desc: "We're committed to offering you the best deals on hotels, attractions, and flights. With our competitive prices and exclusive discounts, you can rest value for your money.",
  },
];

const about = () => {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InnerBanner data={data} />
        <section className="about-section">
          <div className="container">
            <div className="row align-item-center">
              <div className="col-md-6 col-sm-12">
                <div className="about-img">
                  <Image
                    src={"/images/about-txt-img.png"}
                    width={600}
                    height={600}
                    alt="about-txt-img"
                  />
                  <h6>
                    Dolor a consectetur sagittis viverra quisque. Auctor sed
                    hendreri
                  </h6>
                </div>
              </div>
              <div className="col-md-6 col-sm-12">
                <div className="about-img-txt">
                  <h4>Why Choose Us</h4>
                  <h6>
                    Search Flights & Places Hire to our most popular
                    destinations
                  </h6>
                  <p>
                    At FlightFinder, we&lsquo;re dedicated to making your travel
                    experience seamless and stress-free. Here&lsquo;s why savvy
                    travelers trust us for their flight bookings e have been
                    wing with hundreds of clients across all industries. Our
                    dyed-in-the-wool, as we have been wing with hundreds of
                    clients across all industries. Our dyed-in-the-wool, as w
                    The main motto of is to focus on designing, developing,
                    marketing websites, and have expertise in Magento all
                    versions that are performance minded. We have been wing with
                    hundreds of clients across all industries. Our
                    dyed-in-the-wool, as well as{" "}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section
          className="book-advent-sec"
          style={{ backgroundImage: "url('/images/about-txt-img2.png')" }}
        >
          <div className="container">
            <div className="row">
              <div className="col-sm-12">
                <div className="book-advent-txt">
                  <h2>Book Your Adventure Now!</h2>
                  <p>Discover Pakistan&lsquo;s Hidden Treasures</p>
                  <Link href={"/"} className="btn10">
                    Discover Now
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <SameLessTravel />
        <OurMission />
      </Layout>
    </>
  );
};

export default about;
