import Head from "next/head";
import Layout from "../layout/index";
import AmusementBanner from "../Components/AmusementBanner";

import BannerForm from "../Components/BannerForm/BannerForm";
import DestinationCard from "../Components/DestinationCard";
import CounterCard from "../Components/CounterCard";
import FlightCard from "../Components/FlightCard";

const amusement = () => {
  return (
    <>
      <Head>
        <title>Amusement</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <AmusementBanner />
        <BannerForm />
        {/* <PlaneTrip /> */}
        {/* <HotelBook /> */}
        <DestinationCard />
        <CounterCard />
        <FlightCard />
      </Layout>
    </>
  );
};

export default amusement;
