import Head from "next/head";
import BlogsBanner from "../Components/BlogsBanner";
import Layout from "../layout/index";

import BlogList from "../Components/BlogList";
import ExploreByInterests from "../Components/ExploreByInterests";
import RecommendationsSection from "../Components/Recommendations";
import BannerForm from "../Components/BannerForm/BannerForm";
import DestinationCard from "../Components/DestinationCard";
import LocationCard from "../Components/LocationCard";
import Signin from "../Components/Signin";

const blogs = () => {
  return (
    <>
      <Head>
        <title>Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <BlogsBanner />
        {/* <BannerForm /> */}
        {/* <PlaneTrip /> */}
        {/* <HotelBook /> */}
        {/* <DestinationCard /> */}
        {/* <Signin /> */}
        {/* <ExploreByInterests /> */}
        {/* <CounterCard /> */}
        {/* <FlightCard /> */}
        {/* <LocationCard /> */}
        {/* <RecommendationsSection /> */}
        <BlogList />
      </Layout>
    </>
  );
};

export default blogs;
