import Head from "next/head";
import Layout from "../layout/index";

import BannerForm from "../Components/BannerForm/BannerForm";
import HomeBanner from "../Components/HomeBanner";
import FlightStats from "../Components/FlightStats";
import AllFlights from "../Components/AllFlights";

const flights = () => {
  return (
    <>
      <Head>
        <title>Flights</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeBanner />
        <BannerForm />
        <FlightStats />
        <AllFlights />
      </Layout>
    </>
  );
};

export default flights;
