import React, { useCallback, useState } from "react";
import Layout from "../layout/index";
import Head from "next/head";
import Image from "next/image";
import Modal from "react-bootstrap/Modal";
import Button from "react-bootstrap/Button";
import { CiEdit } from "react-icons/ci";
import { useHotelContext } from "../context/HotelDataContext";
import GuestForm from "../Components/GuestForm";
import { formatDate, getLocalItem } from "../utils";
import { countries } from "iso-3166-1-alpha-2";

const initialDetails = {
  gender: "mr",
  firstName: "",
  lastName: "",
  dob: formatDate(new Date().toISOString()),
  nationality: "",
  documentType: "",
  country: "",
};

const initialContactDetails = {
  primaryContact: "",
  nationality: "",
  phone: "",
  email: "",
};

const Passengerdetails = () => {
  const [show, setShow] = useState(false);
  const { formData } = useHotelContext();
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);
  const [adultData, setAdultData] = useState(getLocalItem("adult-guests", {}));
  const [childrenData, setChildrenData] = useState(
    getLocalItem("children-guests", {})
  );
  const [mainGuest, setMainGuest] = useState(
    getLocalItem("main-guest", initialDetails)
  );
  const [contactDetails, setContactDetails] = useState(
    getLocalItem("contact-details", initialContactDetails)
  );

  const handleMainGuestChange = useCallback(
    function (key, value) {
      setMainGuest((prev) => ({
        ...prev,
        [key]: value,
      }));
      localStorage.setItem(
        "main-guest",
        JSON.stringify({
          ...mainGuest,
          [key]: value,
        })
      );
    },
    [mainGuest]
  );

  const handleAdultGuestChange = useCallback(
    function (uid, key, value) {
      setAdultData((prev) => ({
        ...prev,
        [uid]: {
          ...prev[uid],
          [key]: value,
        },
      }));
      localStorage.setItem(
        "adult-guests",
        JSON.stringify({
          ...adultData,
          [uid]: {
            ...adultData[uid],
            [key]: value,
          },
        })
      );
    },
    [adultData]
  );

  const handleChildrenGuestChange = useCallback(
    function (uid, key, value) {
      setChildrenData((prev) => ({
        ...prev,
        [uid]: {
          ...prev[uid],
          [key]: value,
        },
      }));
      localStorage.setItem(
        "children-guests",
        JSON.stringify({
          ...childrenData,
          [uid]: {
            ...childrenData[uid],
            [key]: value,
          },
        })
      );
    },
    [childrenData]
  );

  const handleChange = useCallback(
    function (e) {
      setContactDetails((prev) => ({
        ...prev,
        [e.target.name]: e.target.value,
      }));
      localStorage.setItem(
        "contact-details",
        JSON.stringify({
          ...contactDetails,
          [e.target.name]: e.target.value,
        })
      );
    },
    [contactDetails]
  );

  return (
    <>
      <Head>
        <title>Guest Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout noBanner>
        <Modal show={show} onHide={handleClose} className="cstm_modal">
          <Modal.Header>
            <Modal.Title>Verify Guest Details</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <ul>
              <li>
                <div>
                  <span>Adult</span>
                  <p>{mainGuest?.firstName}</p>
                </div>

                <div>
                  <CiEdit />
                </div>
              </li>
              {Object.values(adultData).map((guest, id) => (
                <li key={id}>
                  <div>
                    <span>Adult</span>
                    <p>{guest?.firstName}</p>
                  </div>

                  <div>
                    <CiEdit />
                  </div>
                </li>
              ))}
              {Object.values(childrenData).map((guest, id) => (
                <li key={id}>
                  <div>
                    <span>Children</span>
                    <p>{guest?.firstName}</p>
                  </div>

                  <div>
                    <CiEdit />
                  </div>
                </li>
              ))}

              <li>
                <div>
                  <span>Contact Details</span>
                  <p>{contactDetails?.email}</p>
                </div>

                <div>
                  <CiEdit />
                </div>
              </li>
            </ul>

            <p>
              Please check that the name entered matches the name on the
              passport. The details can not be edited after you continue,
            </p>
          </Modal.Body>
          <Modal.Footer>
            <Button className="btn10" onClick={handleClose}>
              Review
            </Button>
            <Button className="btn10" onClick={handleClose}>
              Continue
            </Button>
          </Modal.Footer>
        </Modal>

        <section className="passenger-details-sec">
          <div className="container">
            <div className="row">
              <div className="col-sm-12 col-md-6">
                <div className="passenger-details-head">
                  <h6>Guest Details</h6>
                  <p>
                    Please enter names as they Guest names Tips on adding guest
                    names
                  </p>
                </div>
              </div>
              <div className="col-md-8 col-sm-12">
                <div className="passenger-detail-mn">
                  <div className="extra-benifit">
                    <h6>Log in to your account to unlock extra benefits</h6>
                    <ul className="mt-3">
                      <li>
                        <div>
                          <Image
                            alt="img"
                            src={"/images/psngr-dtl-cin-1.png"}
                            width={90}
                            height={70}
                          />
                        </div>
                        <div>
                          <p>
                            Save on your booking when you pay using Cash + Avios
                          </p>
                        </div>
                      </li>
                      <li>
                        <div>
                          <Image
                            alt="img"
                            src={"/images/psngr-dtl-cin-2.png"}
                            width={90}
                            height={70}
                          />
                        </div>
                        <div>
                          <p>Auto-fill your travel details</p>
                        </div>
                      </li>
                    </ul>
                  </div>

                  <GuestForm
                    title={"Main Guest"}
                    onChange={handleMainGuestChange}
                    type={"adult"}
                    data={mainGuest}
                  />

                  {new Array(
                    formData?.adults
                      ? Number(formData?.adults || "0") - 1
                      : undefined
                  )
                    .fill("0")
                    .map((_, key) => (
                      <GuestForm
                        key={key}
                        title={`Guest ${key + 2}`}
                        type={"adult"}
                        data={adultData[key]}
                        onChange={(k, v) => handleAdultGuestChange(key, k, v)}
                      />
                    ))}

                  {new Array(
                    formData?.children && formData?.children !== "0"
                      ? Number(formData?.children || "0") - 1
                      : undefined
                  )
                    .fill("0")
                    .map((_, key) => (
                      <GuestForm
                        key={key}
                        title={`Guest ${
                          key +
                          (formData?.adults
                            ? Number(formData?.adults || "1") + 1
                            : 1)
                        }`}
                        type={"children"}
                        data={childrenData[key]}
                        onChange={(k, v) =>
                          handleChildrenGuestChange(key, k, v)
                        }
                      />
                    ))}

                  <div className="passenger-contact-dtl passenger-detail-inn">
                    <h6>Contact Details</h6>
                    <p>
                      Please provide your contact details so that we can notify
                      you the updates on your flight
                    </p>
                    <div className="row">
                      <div className="col-md-6 col-12">
                        <div className="field">
                          <select>
                            <option value="" selected>
                              Select Primary Contact
                            </option>
                          </select>
                        </div>
                      </div>

                      <div className="col-md-6 col-12">
                        <div className="field">
                          <select
                            value={contactDetails?.nationality}
                            onChange={handleChange}
                            name="nationality"
                          >
                            <option value="">Select Country</option>
                            {Object.keys(countries).map((k, id) => (
                              <option value={k} key={id}>
                                {k}
                              </option>
                            ))}
                          </select>
                        </div>
                      </div>

                      <div className="col-md-6 col-12">
                        <div className="field">
                          <input
                            value={contactDetails?.phone}
                            onChange={handleChange}
                            name="phone"
                            type="tel"
                            placeholder="Phone Number"
                          />
                        </div>
                      </div>

                      <div className="col-md-6 col-12">
                        <div className="field">
                          <input
                            type="email"
                            value={contactDetails?.email}
                            onChange={handleChange}
                            name="email"
                            placeholder="Email"
                          />
                        </div>
                      </div>
                    </div>
                  </div>
                  <div className="passenger-contact-dtl passenger-detail-inn col-12">
                    <div className="field">
                      <input type="checkbox" name="rembeber" />
                      <label htmlFor="rembeber">
                        Remember the above Guest details for future bookings.
                      </label>
                    </div>

                    <div className="btn-pessenger-btn">
                      <button
                        type="submit"
                        className="btn10"
                        onClick={handleShow}
                      >
                        Book Now
                      </button>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-4 col-sm-12">
                <div className="passn-dtl-sidbar">
                  <div className="trip-sum-dtl">
                    <h6>Outbound flight</h6>
                    <div className="flex-div">
                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>DBI</p>
                        <svg
                          width="12"
                          height="11"
                          viewBox="0 0 12 11"
                          fill="none"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            d="M6.90251 0.662507L8.2039 3.30768C8.27858 3.45705 8.42794 3.56354 8.60957 3.59534L11.5212 4.02222C11.9582 4.0863 12.1293 4.61967 11.8199 4.929L9.70765 6.98733C9.57996 7.10488 9.52648 7.28605 9.54769 7.45662L10.0493 10.3581C10.1239 10.7951 9.66524 11.1257 9.27017 10.9233L6.66787 9.54722C6.59102 9.50526 6.50487 9.48327 6.41732 9.48327C6.32976 9.48327 6.24361 9.50526 6.16677 9.54722L3.564 10.9233C3.16939 11.1261 2.71116 10.7951 2.78538 10.3581L3.28694 7.45662C3.30353 7.37059 3.29857 7.28179 3.27251 7.19814C3.24645 7.11448 3.2001 7.03858 3.13758 6.97719L1.02577 4.92854C0.705383 4.61921 0.887015 4.08584 1.32404 4.02176L4.23613 3.59488C4.4067 3.56307 4.55606 3.45659 4.6418 3.29662L5.94272 0.662046C6.1345 0.267436 6.70014 0.267436 6.90251 0.662046V0.662507Z"
                            fill="#666666"
                          />
                        </svg>
                      </div>
                      <div className="trip-sum-img">
                        <p>08:15</p>
                        <Image
                          width={160}
                          height={13}
                          src="/images/trip-sum-img.png"
                          alt="img"
                        />
                      </div>

                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>LDN</p>
                      </div>
                    </div>
                  </div>

                  <div className="trip-sum-dtl">
                    <h6>Outbound flight</h6>
                    <div className="flex-div">
                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>DBI</p>
                      </div>
                      <div className="trip-sum-img">
                        <p>08:15</p>
                        <Image
                          width={160}
                          height={13}
                          src="/images/trip-sum-img.png"
                          alt="img"
                        />
                      </div>

                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>LDN</p>
                      </div>
                    </div>
                  </div>

                  <div className="trip-sum-price">
                    <h6>
                      <span className="prc-ttl">Total trip price:</span>{" "}
                      <span className="prc">603840.00 PKR</span>
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default Passengerdetails;
