import Head from "next/head";
import React, { useState } from "react";
import { toast } from "react-toastify";

import HotelDetailMain from "../Components/Safari/HotelDetailMain";
import Layout from "../layout/index";
import "react-toastify/dist/ReactToastify.css";
import HotelBookingForm from "../Components/HotelBookingForm";
import { Form } from "react-bootstrap";
import { ToastContainer } from "react-toastify";
import { useHotelContext } from "../context/HotelDataContext";
import HotelRoomsViewer from "../Components/HotelRoomsViewer";
import HotelFacilities from "../Components/HotelFacilities";

const Details = () => {
  const { hotelData } = useHotelContext();
  const [formData, setFormData] = useState({
    checkInDate: null,
    checkoutDate: null,
    persons: {
      adults: 1,
      children: 0,
    },
    rooms: 1,
  });
  const newRooms = hotelData?.Rooms
    ? Object.groupBy(hotelData?.Rooms || {}, (r) =>
        !!r && r.Name && r.Name[0] ? r.Name[0] : ""
      )
    : {};

  const validateForm = () => {
    const { checkInDate, checkoutDate, persons } = formData;
    const totalpersons = Object.values(persons).reduce(
      (acc, val) => acc + val,
      0
    );
    if (!checkInDate) {
      toast.error("Please select a check in date.");
      return false;
    }
    if (!checkoutDate) {
      toast.error("Please select a check out date.");
      return false;
    }
    if (totalpersons === 0) {
      toast.error("Please select at least one person.");
      return false;
    }
    return true;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (validateForm()) {
      try {
      } catch (error) {
        toast.error("Error during hotel search. Please try again.");
        console.error("Error during hotel search:", error);
      }
    }
  };

  return (
    <>
      <Head>
        <title>Amusement</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout noBanner>
        <HotelDetailMain />
        <section className="booking_form-sec details-page">
          <div className="container">
            <ToastContainer />
            <Form onSubmit={handleSubmit} className="booking_form-mn">
              <HotelBookingForm formData={formData} setFormData={setFormData} />
              <HotelRoomsViewer rooms={newRooms} />
            </Form>
          </div>
        </section>
        <HotelFacilities facilities={hotelData?.HotelFacilities || []} />
      </Layout>
    </>
  );
};

export default Details;
