import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google"; 
import Header from "@/Components/Header/Header";
import Layout from "../layout/index"
import HomeBanner from "../Components/HomeBanner"
import BannerForm from "../Components/BannerForm/BannerForm";
import PlaneTrip from "../Components/PlaneTrip/PlaneTrip";
import HotelBook from "../Components/HotelBook"
import DestinationCard from "../Components/DestinationCard"
import CounterCard from "../Components/CounterCard"
import FlightCard from "../Components/FlightCard"


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HomeBanner/>
        <BannerForm/>
        <PlaneTrip/>
        <HotelBook/>
        <DestinationCard/>
        <CounterCard/>
        <FlightCard/>
      </Layout>
     
    </>
  );
}
