import React, { useState } from "react";
import Layout from "../layout/index";
import Head from "next/head";
import InnerBanner from "../Components/InnerBanner/InnerBanner";
import Image from "next/image";
import Modal from "react-bootstrap/Modal";
import Button from "react-bootstrap/Button";
import { CiEdit } from "react-icons/ci";

const data = [
  {
    eyeBrow: "",
    title: "Passenger Details.",
    imageUrl: "/images/contact-banner.png",
  },
];

const Passengerdetails = () => {
  const [show, setShow] = useState(false);

  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);

  return (
    <>
      <Head>
        <title>Passenger Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InnerBanner data={data} />

        <Modal show={show} onHide={handleClose} className="cstm_modal">
          <Modal.Header>
            <Modal.Title>Verify Passenger Details</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <ul>
              <li>
                <div>
                  <span>Adult</span>
                  <p>David</p>
                </div>

                <div>
                  <CiEdit />
                </div>
              </li>
              <li>
                <div>
                  <span>Adult</span>
                  <p>David</p>
                </div>

                <div>
                  <CiEdit />
                </div>
              </li>

              <li>
                <div>
                  <span>Contact Details</span>
                  <p>example@gmail.com</p>
                </div>

                <div>
                  <CiEdit />
                </div>
              </li>
            </ul>

            <p>
              Please check that the name entered matches the name on the
              passport. The details can not be edited after you continue,
            </p>
          </Modal.Body>
          <Modal.Footer>
            <Button className="btn10" onClick={handleClose}>
              Review
            </Button>
            <Button className="btn10" onClick={handleClose}>
              Continue
            </Button>
          </Modal.Footer>
        </Modal>

        <section className="passenger-details-sec">
          <div className="container">
            <div className="row">
              <div className="col-sm-12 col-md-6">
                <div className="passenger-details-head">
                  <h6>Passenger Details</h6>
                  <p>
                    Please enter names as they appear on passport or travel
                    documents Tips on adding passenger name
                  </p>
                </div>
              </div>
              <div className="col-md-8 col-sm-12">
                <div className="passenger-detail-mn">
                  <div className="extra-benifit">
                    <h6>Log in to your account to unlock extra benefits</h6>
                    <ul className="mt-3">
                      <li>
                        <div>
                          <Image
                            alt="img"
                            src={"/images/psngr-dtl-cin-1.png"}
                            width={90}
                            height={70}
                          />
                        </div>
                        <div>
                          <p>
                            Save on your booking when you pay using Cash + Avios
                          </p>
                        </div>
                      </li>
                      <li>
                        <div>
                          <Image
                            alt="img"
                            src={"/images/psngr-dtl-cin-2.png"}
                            width={90}
                            height={70}
                          />
                        </div>
                        <div>
                          <p>Auto-fill your travel details</p>
                        </div>
                      </li>
                    </ul>
                  </div>
                  <div className="passenger-detail-inn">
                    <h6>Passenger 1 (Adult)</h6>

                    <form action="#">
                      <div className="row">
                        <div className="col-12">
                          <div className="field">
                            <label>Title</label>
                            <ul>
                              <li>
                                <input type="radio" id="gender" />
                                <label htmlFor="gender">Mr</label>
                              </li>
                              <li>
                                <input type="radio" id="gender" />
                                <label htmlFor="gender">Mrs</label>
                              </li>
                              <li>
                                <input type="radio" id="gender" />
                                <label htmlFor="gender">Ms</label>
                              </li>
                            </ul>
                          </div>
                        </div>
                        <div className="col-sm-12 col-md-6">
                          <div className="field">
                            <input
                              type="text"
                              placeholder="Full Name/Middle Name"
                            />
                          </div>
                        </div>
                        <div className="col-sm-12 col-md-6">
                          <div className="field">
                            <input type="text" placeholder="Last Name" />
                          </div>
                        </div>

                        <div className="col-sm-12 col-md-6">
                          <div className="field date-birth">
                            <p>Date of birth</p>
                            <input type="date" />
                          </div>
                        </div>

                        <div className="col-sm-12 col-md-6">
                          <div className="field date-birth">
                            <select>
                              <option value="Nationality" selected>
                                Nationality
                              </option>
                              <option value="Nationality1">Nationality1</option>
                            </select>
                          </div>
                        </div>
                        <div className="col-sm-12 col-md-12">
                          <div className="travel-doc-head">
                            <h6>Travel Documents</h6>
                          </div>
                        </div>
                        <div className="col-sm-12 col-md-6">
                          <div className="field date-birth">
                            <select>
                              <option value="Nationality" selected>
                                Nationality
                              </option>
                              <option value="Nationality1">Nationality1</option>
                            </select>
                          </div>
                        </div>

                        <div className="col-sm-12 col-md-6">
                          <div className="field date-birth">
                            <select>
                              <option value="Select Country" selected>
                                Select Country
                              </option>
                              <option value="SelectCountry1">
                                Select Country
                              </option>
                            </select>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>

                  <div className="passenger-expand">
                    <h6>Passenger 2 (Adult)</h6>
                    <p>Expand to add details</p>
                  </div>

                  <div className="passenger-contact-dtl passenger-detail-inn">
                    <h6>Contact Details</h6>
                    <p>
                      Please provide your contact details so that we can notify
                      you the updates on your flight
                    </p>
                    <form action="#">
                      <div className="row">
                        <div className="col-md-6 col-12">
                          <div className="field">
                            <select>
                              <option value="Nationality" selected>
                                Select Primary Contact
                              </option>
                              <option value="Nationality1">Nationality1</option>
                            </select>
                          </div>
                        </div>

                        <div className="col-md-6 col-12">
                          <div className="field">
                            <select>
                              <option value="Nationality" selected>
                                Select Country
                              </option>
                              <option value="Nationality1">Nationality1</option>
                            </select>
                          </div>
                        </div>

                        <div className="col-md-6 col-12">
                          <div className="field">
                            <input type="tel" placeholder="Phone Number" />
                          </div>
                        </div>

                        <div className="col-md-6 col-12">
                          <div className="field">
                            <input type="email" placeholder="Email" />
                          </div>
                        </div>

                        <div className="col-12">
                          <div className="field">
                            <input type="checkbox" name="rembeber" />
                            <label htmlFor="rembeber">
                              Remember the above passenger details for future
                              bookings.
                            </label>
                          </div>

                          <div className="btn-pessenger-btn">
                            <button
                              type="submit"
                              className="btn10"
                              onClick={handleShow}
                            >
                              Select Your Seats
                            </button>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
              <div className="col-md-4 col-sm-12">
                <div className="passn-dtl-sidbar">
                  <h6>Your trip summary</h6>
                  <div className="trip-sum-dtl">
                    <h6>Outbound flight</h6>
                    <div className="flex-div">
                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>DBI</p>
                      </div>
                      <div className="trip-sum-img">
                        <p>08:15</p>
                        <Image
                          width={160}
                          height={13}
                          src="/images/trip-sum-img.png"
                          alt="img"
                        />
                      </div>

                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>LDN</p>
                      </div>
                    </div>
                  </div>

                  <div className="trip-sum-dtl">
                    <h6>Outbound flight</h6>
                    <div className="flex-div">
                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>DBI</p>
                      </div>
                      <div className="trip-sum-img">
                        <p>08:15</p>
                        <Image
                          width={160}
                          height={13}
                          src="/images/trip-sum-img.png"
                          alt="img"
                        />
                      </div>

                      <div className="trip-dv-1">
                        <span>Thu, 30 May</span>
                        <p>10:25</p>
                        <p>LDN</p>
                      </div>
                    </div>
                  </div>

                  <div className="trip-sum-price">
                    <h6>
                      <span className="prc-ttl">Total trip price:</span>{" "}
                      <span className="prc">603840.00 PKR</span>
                    </h6>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default Passengerdetails;
