import Head from "next/head";
import React, { useState } from "react";
import Layout from "../layout/index";
import Image from "next/image";
import Link from "next/link";

const Payment = () => {
  const [noBanner, setNoBanner] = useState(true);
  return (
    <>
      <Head>
        <title>Seat Selection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout noBanner={noBanner}>
        <section className="payment-sec">
          <div className="container">
            <div className="row">
              <div className="col-md-8 col-sm-12">
                <div className="payment-mn-dv">
                  <div className="pay-dv">
                    <h6>Pay in your card currency</h6>
                    <p>
                      As a Visa or Mastercard credit cardholder, you can pay in
                      the currency of the country where your card was issued.
                    </p>
                  </div>
                  <div className="payment-form-mn">
                    <h6>Select your preferred payment method</h6>
                    <p>Debit / Credit cards</p>
                    <Image
                      src={"/images/card-img.png"}
                      width={350}
                      height={45}
                      alt="img"
                    />
                    <form action="#">
                      <div className="row">
                        <div className="col-md-12">
                          <div className="field">
                            <label>Debit/ Credit Card Number</label>
                            <input
                              type="text"
                              placeholder="Enter the card number"
                            />
                          </div>
                        </div>
                        <div className="col-md-4">
                          <div className="field">
                            <label>Card Expiry</label>
                            <select>
                              <option value="Month" selected>
                                Month
                              </option>
                            </select>
                          </div>
                        </div>
                        <div className="col-md-4">
                          <div className="field">
                            <label>Year</label>
                            <select>
                              <option value="Month" selected>
                                Year
                              </option>
                            </select>
                          </div>
                        </div>
                        <div className="col-md-4">
                          <div className="field">
                            <label>CVV/CVC</label>
                            <input type="text" placeholder="CVV?CVC" />
                          </div>
                        </div>
                        <div className="col-md-12">
                          <div className="field">
                            <label>Name on Card</label>
                            <input
                              type="text"
                              placeholder="Enter the name printed on Card"
                            />
                          </div>
                        </div>
                        <div className="col-md-12">
                          <div className="field">
                            <label>Email Address (optional)</label>
                            <input
                              type="email"
                              placeholder="Email Address (optional)"
                            />
                          </div>
                        </div>
                      </div>
                    </form>

                    <div className="billing-from">
                      <h6>Billing Address</h6>
                      <div className="row">
                        <div className="col-md-12">
                          <div className="field">
                            <label>Country Region</label>
                            <select>
                              <option value="Country Region" selected>
                                Country Region
                              </option>
                            </select>
                          </div>
                        </div>
                        <div className="col-md-12">
                          <div className="field">
                            <label>Postal/zip code</label>
                            <input
                              type="number"
                              placeholder="Postal/zip code"
                            />
                          </div>
                        </div>
                        <div className="col-md-12">
                            <div className="field">
                                <label>Address line 1</label>
                                <input type="text" placeholder="Address line 1" />
                            </div>
                        </div>
                        <div className="col-md-12">
                            <div className="field">
                                <label>Address line 2 (optional)</label>
                                <input type="text" placeholder="Address line 2 (optional)" />
                            </div>
                        </div>
                        <div className="col-md-12">
                            <div className="field">
                                <label>Town/ City</label>
                                <input type="text" placeholder="Town/ City" />
                            </div>
                        </div>
                        <div className="col-md-12">
                            <div className="field">
                                <label>State (optional)</label>
                                <input type="text" placeholder="State (optional)" />
                            </div>
                        </div>

                        <div className="col-md-12">
                            <div className="field checkbox-field">
                                <input type="checkbox"/>
                                <p>I agree to the Travel Mania <Link href={''}>terms and conditions.</Link></p>
                            </div>
                        </div>
                      </div>
                    </div>
                    <div className="btn-field-sub">
                      <Link href={""} className="btn10">Confirm Payment</Link>
                      <Link href={""} className="btn-back">Back</Link>
                    </div>
                    

                  </div>
                </div>
              </div>

              <div className="col-md-4 col-sm-12">
                    <div className="book-sum-dv">
                        <p>Booking summary</p>
                        <h6>Dubai  - London </h6>
                        <p>Thu, 30 May - Sat, 15 Jun - Return trip (2 adults)</p>
                        <h5>Total : PKR 56809.00</h5>
                    </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default Payment;
