import React from "react";
import Layout from "../layout/index";
import HomeBanner from "../Components/HomeBanner";
import BannerForm from "../Components/BannerForm/BannerForm";
import Head from "next/head";
import { GoSearch } from "react-icons/go";
import { LiaExchangeAltSolid } from "react-icons/lia"; 
import { Pagination } from 'react-bootstrap';
import PaginationComponent from '../Components/pagination/PaginationComponent';
import { Slider, RangeSlider } from 'rsuite';

const search = () => {
 
    
  return (
    <>
      <Head>
        <title>Search Flight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <HomeBanner />
        <BannerForm />
        <section className="flight-search-sec">
          <div className="container">
            <div className="row">
              <div className="col-12">
                <div className="search-main-bar">
                  <div className="search-main">
                    <div className="icn">
                      <GoSearch />
                    </div>
                    <div className="icn-txt">
                      <div>
                        <span>Dubai</span>
                        <LiaExchangeAltSolid /> <span>England</span>
                      </div>
                      <p>
                        <span>1 adult | ecomomy</span>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="row">
              <div className="col-md-4 col-xl-3 col-lg-3 col-sm-12">
                <div className="search-sidebar">
                  <div className="search-sidebar-head">
                    <h3>Filters</h3>
                    <button className="btn10">Reset</button>
                  </div>
                  <div className="search-sidebar-filter">
                    <div className="sidebar-filter-inn">
                        <h6>Flight</h6>
                        <ul>
                            <li><input type="checkbox" name="flight-option-1" id="flight-option-1"  /> <label htmlFor="flight-option-1"> All Flight</label></li>
                            <li><input type="checkbox" name="flight-option-2" id="flight-option-2"  /> <label htmlFor="flight-option-1"> Connected Flight</label></li>
                            <li><input type="checkbox" name="flight-option-3" id="flight-option-3"  /> <label htmlFor="flight-option-1"> Direct Flight</label></li>
                        </ul>
                    </div> 
                    <div className="sidebar-filter-inn-price">
                        <h6>Price Range</h6>
                        
                        <RangeSlider defaultValue={[0, 50]} onChange={value => {
                            console.log(value);
                          }} />
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-md-8 col-xl-9 col-lg-9 col-sm-12">
                <div className="search-pg-main-dv">
                    <p>236 Results</p>
                    <PaginationComponent itemsPerPage={5} totalItems={20} />
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default search;
