import Signin from "../Components/Signin";
import Head from "next/head";
import { useState } from "react";
import { Button, Card, Col, Container, Form, Row } from "react-bootstrap";
import BannerForm from "../Components/BannerForm/BannerForm";
import Layout from "../layout/index";
import AmusementBanner from "../Components/AmusementBanner/index";
import ModernVision from "../../public/images/modern-vision.svg";
import Deal1 from "../../public/images/deal-1.svg";
import Deal2 from "../../public/images/deal-2.svg";
import Deal3 from "../../public/images/deal-3.svg";

import Image from "next/image";

const searchResults = [
  {
    image: ModernVision,
    title:
      "Modern Visions of Dubai - Dubai Marina Cruise and Dubai Frame Visit",
    description:
      "With this tour you get the chance to discover Dubai's Past, Present and Future. Experience a Pan...",
    price: "US$499",
    cancellation: "Free cancellation available",
  },
  {
    image: ModernVision,
    title:
      "Modern Visions of Dubai - Dubai Marina Cruise and Dubai Frame Visit",
    description:
      "With this tour you get the chance to discover Dubai's Past, Present and Future. Experience a Pan...",
    price: "US$499",
    cancellation: "Free cancellation available",
  },
  {
    image: ModernVision,
    title:
      "Modern Visions of Dubai - Dubai Marina Cruise and Dubai Frame Visit",
    description:
      "With this tour you get the chance to discover Dubai's Past, Present and Future. Experience a Pan...",
    price: "US$499",
    cancellation: "Free cancellation available",
  },
];

const deals = [
  {
    image: Deal1,
    title: "Dubai Top 20 Must-see Attractions with Burj Khalifa and Souks",
    discount: "20% OFF",
    price: "From US$49.00",
  },
  {
    image: Deal2,
    title: "Dubai Top 20 Must-see Attractions with Burj Khalifa and Souks",
    discount: "20% OFF",
    price: "From US$49.00",
  },
  {
    image: Deal3,
    title: "Dubai Top 20 Must-see Attractions with Burj Khalifa and Souks",
    discount: "20% OFF",
    price: "From US$49.00",
  },
];

const DubaiAttractions = () => {
  const [filters, setFilters] = useState({
    category: [],
    price: [],
    showWith: [],
    reviewScore: [],
    location: [],
    language: [],
  });

  const handleFilterChange = (filterType, value) => {
    setFilters((prevFilters) => {
      const updatedFilter = [...prevFilters[filterType]];
      if (updatedFilter.includes(value)) {
        return {
          ...prevFilters,
          [filterType]: updatedFilter.filter((item) => item !== value),
        };
      } else {
        return {
          ...prevFilters,
          [filterType]: [...updatedFilter, value],
        };
      }
    });
  };

  return (
    <>
      <Head>
        <title>Search Result</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <AmusementBanner />
        <BannerForm />
        <Container className="mt-5 d-flex flex-column align-items-end">
          <Row>
            <Col md={3}>
              <h5>Filter by</h5>
              <Form>
                <h6>Category</h6>
                {[
                  "Tours",
                  "Museums, arts & culture",
                  "Afternoon",
                  "Entertainment & tickets",
                  "Food & drinks",
                  "Nature & outdoor",
                  "Travel services & rentals",
                  "Workshops & classes",
                ].map((category, index) => (
                  <Form.Check
                    key={index}
                    type="checkbox"
                    label={category}
                    onChange={() => handleFilterChange("category", category)}
                  />
                ))}

                <h6>Price</h6>
                {[
                  "US$0 - US$22",
                  "US$22 - US$44",
                  "US$44 - US$88",
                  "US$88 - US$176",
                  "US$176+",
                ].map((price, index) => (
                  <Form.Check
                    key={index}
                    type="checkbox"
                    label={price}
                    onChange={() => handleFilterChange("price", price)}
                  />
                ))}

                <h6>Show results with</h6>
                {["Free cancellation", "Skip the line", "Arabic"].map(
                  (option, index) => (
                    <Form.Check
                      key={index}
                      type="checkbox"
                      label={option}
                      onChange={() => handleFilterChange("showWith", option)}
                    />
                  )
                )}

                <h6>Review score</h6>
                {["4.5 & up", "4.0 & up", "3.0 & up"].map((score, index) => (
                  <Form.Check
                    key={index}
                    type="checkbox"
                    label={score}
                    onChange={() => handleFilterChange("reviewScore", score)}
                  />
                ))}

                <h6>Location</h6>
                {["Dubai", "Abu Dhabi", "Sharjah"].map((location, index) => (
                  <Form.Check
                    key={index}
                    type="checkbox"
                    label={location}
                    onChange={() => handleFilterChange("location", location)}
                  />
                ))}

                <h6>Language</h6>
                {["English", "Arabic"].map((language, index) => (
                  <Form.Check
                    key={index}
                    type="checkbox"
                    label={language}
                    onChange={() => handleFilterChange("language", language)}
                  />
                ))}
              </Form>
            </Col>
            <Col md={9}>
              <h5>Dubai Attractions</h5>
              <div className="mb-3">
                <Button variant="outline-primary" className="mr-2">
                  Our top picks
                </Button>
                <Button variant="outline-primary" className="mr-2">
                  Most popular
                </Button>
                <Button variant="outline-primary" className="mr-2">
                  Lowest price
                </Button>
                <Button variant="outline-primary">Best reviewed</Button>
              </div>
              {searchResults.map((result, index) => (
                <Card key={index} className="mb-4">
                  <Row noGutters>
                    <Col md={3}>
                      <Image
                        src={result.image}
                        alt={result.title}
                        className="object-fit-cover"
                      />
                      {/* <Card.Img src={result.image} /> */}
                    </Col>
                    <Col md={8}>
                      <Card.Body>
                        <Card.Title>{result.title}</Card.Title>
                        <Card.Text>{result.description}</Card.Text>
                        <Card.Text className="text-muted">
                          {result.cancellation}
                        </Card.Text>
                        <Card.Text className="font-weight-bold">
                          {result.price}
                        </Card.Text>
                        <Button variant="outline-primary">
                          See availability
                        </Button>
                      </Card.Body>
                    </Col>
                  </Row>
                </Card>
              ))}
            </Col>
          </Row>
          <Col md={9} className="my-4 ps-5">
            <Signin />
          </Col>
          <Col md={9} className="ps-5">
            {searchResults.map((result, index) => (
              <Card key={index} className="mb-4">
                <Row noGutters>
                  <Col md={3}>
                    <Image
                      src={result.image}
                      alt={result.title}
                      className="object-fit-cover"
                    />
                  </Col>
                  <Col md={8}>
                    <Card.Body>
                      <Card.Title>{result.title}</Card.Title>
                      <Card.Text>{result.description}</Card.Text>
                      <Card.Text className="text-muted">
                        {result.cancellation}
                      </Card.Text>
                      <Card.Text className="font-weight-bold">
                        {result.price}
                      </Card.Text>
                      <Button variant="outline-primary">
                        See availability
                      </Button>
                    </Card.Body>
                  </Col>
                </Row>
              </Card>
            ))}
          </Col>
          <Col md={9} className="ps-5">
            <Row>
              <h5 className="mb-4 text-black">Deals and Discounts</h5>
              {deals.map((deal, index) => (
                <Col md={4} key={index}>
                  <Card className="mb-4">
                    <Image
                      src={deal.image}
                      alt={deal.title}
                      className="object-fit-cover"
                      width={300}
                    />
                    <Card.ImgOverlay className="d-flex bg-black bg-opacity-25">
                      <div className="discount-badge">{deal.discount}</div>
                      <Card.Body className="align-self-end">
                        <Card.Title className="text-white fs-5">
                          {deal.title}
                        </Card.Title>
                        <Card.Text className="text-white fs-6">
                          {deal.price}
                        </Card.Text>
                      </Card.Body>
                    </Card.ImgOverlay>
                  </Card>
                </Col>
              ))}
            </Row>
          </Col>
          <Col md={9} className="ps-5">
            {searchResults.map((result, index) => (
              <Card key={index} className="mb-4">
                <Row noGutters>
                  <Col md={3}>
                    <Image
                      src={result.image}
                      alt={result.title}
                      className="object-fit-cover"
                    />
                  </Col>
                  <Col md={8}>
                    <Card.Body>
                      <Card.Title>{result.title}</Card.Title>
                      <Card.Text>{result.description}</Card.Text>
                      <Card.Text className="text-muted">
                        {result.cancellation}
                      </Card.Text>
                      <Card.Text className="font-weight-bold">
                        {result.price}
                      </Card.Text>
                      <Button variant="outline-primary">
                        See availability
                      </Button>
                    </Card.Body>
                  </Col>
                </Row>
              </Card>
            ))}
          </Col>
        </Container>
      </Layout>
    </>
  );
};

export default DubaiAttractions;
