import Head from "next/head";
import React from "react";
import Layout from "../layout/index";
import InnerBanner from "@/Components/InnerBanner/InnerBanner";
import Image from "next/image";
import Accordion from "react-bootstrap/Accordion";
import { IoMdCheckmark } from "react-icons/io";
const data = [
  {
    eyeBrow: "",
    title: "Seat Selection",
    imageUrl: "/images/contact-banner.png",
  },
];

const seatselection = () => {
  return (
    <>
      <Head>
        <title>Seat Selection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InnerBanner data={data} />

        <section className="seat_select-sec">
          <div className="container">
            <div className="row">
              <div className="col-md-12">
                <div className="seat_select-innr">
                  <div className="seat_select-innr-ardian">
                    <div className="seat_select-innr-icn">
                      <div>
                        <Image
                          src={"/images/seat-plane-icon.png"}
                          width={90}
                          height={90}
                          alt="img"
                        />
                      </div>
                      <div>
                        <span>Thu, 30 May 2024</span>
                        <p>Dubai (DBI) - London (LDN)</p>
                      </div>
                    </div>

                    <Accordion defaultActiveKey="0">
                      <Accordion.Item eventKey="0">
                        <Accordion.Header>
                          <div>
                            <h6>DBI - LDN</h6>
                            <div>
                              <span>Flight duration</span>
                              <span>8hrs 15minutes</span>
                            </div>
                          </div>
                        </Accordion.Header>
                        <Accordion.Body>
                          <div className="flight_acordian-inn">
                            <div className="flight_acordian-lft">
                              <ul className="seat-ul-num">
                                <li>
                                  <div className="seat-numb">19D</div>
                                  <div>
                                    <h6>David</h6>
                                    <ul>
                                      <li>
                                        <IoMdCheckmark /> <span>Selected</span>
                                      </li>
                                      <li>
                                        <span>8667:00 PKR</span>
                                      </li>
                                    </ul>
                                  </div>
                                </li>
                                <li>
                                  <div className="seat-numb">19D</div>
                                  <div>
                                    <h6>David</h6>
                                    <ul>
                                      <li>
                                        <IoMdCheckmark /> <span>Selected</span>
                                      </li>
                                      <li>
                                        <span>8667:00 PKR</span>
                                      </li>
                                    </ul>
                                  </div>
                                </li>
                              </ul>
                              <ul className="seat-ul-ttl">
                                <li>
                                  <p>Sub total</p>
                                </li>
                                <li>
                                  <p>8667:00 PKR</p>
                                </li>
                              </ul>
                            </div>
                            <div className="flight_acordian-cntr">
                              <ul className="seats-ul">
                                <li>
                                  <div>
                                    <Image
                                      src={"/images/seat-1.png"}
                                      width={44}
                                      height={44}
                                      alt="img"
                                    />
                                  </div>
                                  <div>
                                    <p>Extra legroom</p>
                                    <span>18452.0 PKR</span>
                                  </div>
                                </li>
                                <li>
                                  <div>
                                    <Image
                                      src={"/images/seat-2.png"}
                                      width={44}
                                      height={44}
                                      alt="img"
                                    />
                                  </div>
                                  <div>
                                    <p>Extra legroom</p>
                                    <span>18452.0 PKR</span>
                                  </div>
                                </li>
                                <li>
                                  <div>
                                    <Image
                                      src={"/images/seat-3.png"}
                                      width={44}
                                      height={44}
                                      alt="img"
                                    />
                                  </div>
                                  <div>
                                    <p>Extra legroom</p>
                                    <span>18452.0 PKR</span>
                                  </div>
                                </li>
                                <li>
                                  <div>
                                    <Image
                                      src={"/images/seat-4.png"}
                                      width={44}
                                      height={44}
                                      alt="img"
                                    />
                                  </div>
                                  <div>
                                    <p>Extra legroom</p>
                                    <span>18452.0 PKR</span>
                                  </div>
                                </li>
                              </ul>

                              <div className="seat-center-mn">
                                <ul className="seat-numbers">
                                    <li><p>01</p></li>
                                    <li><p>02</p></li>
                                </ul>
                                <div>
                                  <ul className="seat-alpha">
                                    <li>
                                      <p>A</p>
                                    </li>
                                    <li>
                                      <p>B</p>
                                    </li>
                                    <li>
                                      <p>C</p>
                                    </li>
                                    <li>
                                      <p>D</p>
                                    </li>
                                    <li>
                                      <p>E</p>
                                    </li>
                                    <li>
                                      <p>F</p>
                                    </li>
                                    <li>
                                      <p>G</p>
                                    </li>
                                    <li>
                                      <p>H</p>
                                    </li>
                                    <li>
                                      <p>I</p>
                                    </li>
                                  </ul>
                                  <ul className="seat-alpha">
                                    <li>
                                      <Image
                                        src={"/images/seat-1.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-2.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-3.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-4.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-1.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-2.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-3.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-4.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-3.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-1.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-2.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-3.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-4.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-1.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-2.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-3.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-4.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                    <li>
                                      <Image
                                        src={"/images/seat-3.png"}
                                        width={40}
                                        height={40}
                                        alt="img"
                                      />
                                    </li>
                                  </ul>
                                </div>
                              </div>
                            </div>
                            <div className="flight_acordian-rgt">
                              <h6>Economy</h6>
                              <Image
                                src={"/images/plane-img.png"}
                                width={100}
                                height={100}
                                alt="planeImage"
                              />
                            </div>
                          </div>
                        </Accordion.Body>
                      </Accordion.Item>
                      <Accordion.Item eventKey="1">
                        <Accordion.Header>
                          <div>
                            <h6>DBI - LDN</h6>
                            <div>
                              <span>Flight duration</span>
                              <span>8hrs 15minutes</span>
                            </div>
                          </div>
                        </Accordion.Header>
                        <Accordion.Body>
                          Lorem ipsum dolor sit amet, consectetur adipiscing
                          elit, sed do eiusmod tempor incididunt ut labore et
                          dolore magna aliqua. Ut enim ad minim veniam, quis
                          nostrud exercitation ullamco laboris nisi ut aliquip
                          ex ea commodo consequat. Duis aute irure dolor in
                          reprehenderit in voluptate velit esse cillum dolore eu
                          fugiat nulla pariatur. Excepteur sint occaecat
                          cupidatat non proident, sunt in culpa qui officia
                          deserunt mollit anim id est laborum.
                        </Accordion.Body>
                      </Accordion.Item>
                    </Accordion>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default seatselection;
