import Head from "next/head";
import React, { useState } from "react";
import FlightInfoAccordion from "../Components/FlightInfoAccordion";
import Layout from "../layout/index";
import { Button } from "react-bootstrap";
import { useFlightContext } from "../context/FlightDataContext";

const SeatSelection = () => {
  const [continueState, setContinueState] = useState(false);
  const { flightInfo } = useFlightContext();
  return (
    <>
      <Head>
        <title>Seat Selection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout noBanner>
        <section className="seat_select-sec">
          <div className="container">
            <h4 className="mb-4">Seat Selection</h4>
            <div className="row">
              <div className="col-md-12">
                <div className="seat_select-innr">
                  <FlightInfoAccordion
                    continueState={continueState}
                    setContinueState={setContinueState}
                  />
                  {flightInfo?.tripType !== "one-way" && (
                    <>
                      <hr />
                      <FlightInfoAccordion
                        continueState={continueState}
                        setContinueState={setContinueState}
                        isReturn
                      />
                    </>
                  )}

                  <Button
                    onClick={() => setContinueState((pre) => !pre)}
                    className="btn10 right-0 mt-3"
                  >
                    Continue
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default SeatSelection;
