import Head from "next/head";
import React from "react";
import FlightInfoAccordion from "../Components/FlightInfoAccordion";
import Layout from "../layout/index";

const SeatSelection = () => {
  return (
    <>
      <Head>
        <title>Seat Selection</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout noBanner>
        <section className="seat_select-sec">
          <div className="container">
            <h4 className="mb-4">Seat Selection</h4>
            <div className="row">
              <div className="col-md-12">
                <div className="seat_select-innr">
                  <FlightInfoAccordion />
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default SeatSelection;
