import Head from "next/head";
import Layout from "../layout/index";

import BannerForm from "../Components/BannerForm/BannerForm";
import VisaBanner from "../Components/VisaBanner";
import FlightStats from "../Components/FlightStats";
import AllFlights from "../Components/AllFlights";

const visa = () => {
  return (
    <>
      <Head>
        <title>Visa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <VisaBanner />
      </Layout>
    </>
  );
};

export default visa;
