import Head from "next/head";
import Layout from "../layout/index";

import VisaBanner from "../Components/VisaBanner";
import VisaChange from "../Components/VisaChange";
import ExtendVisa from "../Components/ExtendVisa";

const visa = () => {
  return (
    <>
      <Head>
        <title>Visa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <VisaBanner />
        <VisaChange />
        <ExtendVisa />
      </Layout>
    </>
  );
};

export default visa;
